version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: "16"
    commands:
      - npm install -g npm@7
  build:
    commands:
      # install & build root-config
      - cd ${CODEBUILD_SRC_DIR}/frontend/root-config
      - npm install 
      - npm run lint
      - npm run build:webpack
      # install & build root-config
      - cd ${CODEBUILD_SRC_DIR}/frontend/main-app
      - npm install 
      - npm run lint
      - npm run build:webpack
